# Generated by Django 3.1.1 on 2020-09-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('era', models.CharField(max_length=20)),
                ('article', models.CharField(max_length=16384)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
