# Generated by Django 3.1.1 on 2020-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='article',
            field=models.TextField(),
        ),
    ]
