# Generated by Django 3.1.1 on 2020-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0002_auto_20200925_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('textbook', models.FileField(upload_to='')),
            ],
        ),
    ]
