# Generated by Django 3.1.1 on 2020-10-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0003_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='subject',
            field=models.CharField(choices=[('HM', 'Гармония'), ('ML', 'Музыкальная литература')], max_length=2, null=True),
        ),
    ]
