# Generated by Django 3.1.1 on 2020-10-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0004_textbook_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='textbook',
            field=models.FileField(upload_to='textbooks/'),
        ),
    ]
