# Generated by Django 3.1.1 on 2020-10-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0005_auto_20201007_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='date_of_birth',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
