# Generated by Django 3.1.1 on 2020-10-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0006_composer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='nationality',
            field=models.CharField(choices=[('FR', 'Франция'), ('EN', 'Англия'), ('GR', 'Германия'), ('PL', 'Польша'), ('IL', 'Италия'), ('RU', 'Россия')], max_length=2, null=True),
        ),
    ]
